#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.0.{build}-{branch}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017
clone_folder: C:\taichi

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: x64
configuration: Release

build_script:
  - cd C:\
  - curl https://github.com/yuanming-hu/taichi_assets/releases/download/llvm8/taichi-llvm-8.0.1-msvc2017.zip -LO
  - 7z x taichi-llvm-8.0.1-msvc2017.zip -otaichi_llvm
  - curl https://github.com/yuanming-hu/taichi_assets/releases/download/llvm8/clang-7.0.1-win.zip -LO
  - 7z x clang-7.0.1-win.zip -otaichi_clang
  - set PATH=%PATH%;C:\taichi_clang\bin
  - set TAICHI_REPO_DIR=C:\taichi
  - set PYTHONPATH=%TAICHI_REPO_DIR%/python
  - set PYTHON=C:\Python36-x64\python.exe
  - clang --version
  - cd C:\taichi
  - "%PYTHON% dev_setup.py ci"
  - mkdir build
  - cd build
  - cmake .. -G"Visual Studio 15 2017 Win64" -DPYTHON_EXECUTABLE="%PYTHON%" -DLLVM_DIR="C:\taichi_llvm\lib\cmake\llvm"
  - msbuild /p:Configuration=RelWithDebInfo /p:Platform=x64 /m taichi.sln
  - cd ..
  - '%PYTHON% -c "import taichi"'
  - "%PYTHON% examples/laplace.py"
  - "%PYTHON% -m pytest tests/python/test_abs.py -s"
  #- "%PYTHON% -m taichi test"
